"""Major Tables Modified

Revision ID: 64ccfccd6966
Revises: c4ece44f5237
Create Date: 2026-04-17 17:01:59.546791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '64ccfccd6966'
down_revision: Union[str, Sequence[str], None] = 'c4ece44f5237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = postgresql.ENUM('USER', 'ADMIN', 'VENUE_MANAGER', 'SCORE_UPDATER', name='userrole')
    user_role_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('Teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('team_name')
    )
    op.create_table('Venue',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('venue_name', sa.String(), nullable=False),
    sa.Column('venue_address', sa.String(), nullable=True),
    sa.Column('Venue_Capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('venue_id'),
    sa.UniqueConstraint('venue_name')
    )
    op.create_table('Match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team1_id', sa.Integer(), nullable=False),
    sa.Column('team2_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('match_status', sa.Enum('STARTED', 'ABANDONED', 'IN_PROGRESS', 'YET_TO_START', name='matchstatus'), nullable=True),
    sa.CheckConstraint('team1_id <> team2_id', name='ck_team1_team2_different'),
    sa.ForeignKeyConstraint(['team1_id'], ['Teams.team_id'], ),
    sa.ForeignKeyConstraint(['team2_id'], ['Teams.team_id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.venue_id'], ),
    sa.PrimaryKeyConstraint('match_id'),
    sa.UniqueConstraint('venue_id', 'match_date', name='uq_venue_match_date')
    )
    op.create_table('PointsTable',
    sa.Column('points_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('no_result', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Teams.team_id'], ),
    sa.PrimaryKeyConstraint('points_id'),
    sa.UniqueConstraint('team_id', 'season_id', name='uq_team_season_points')
    )
    op.create_table('Venue_Avaialability',
    sa.Column('venue_availability_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('venue_availability_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.venue_id'], ),
    sa.PrimaryKeyConstraint('venue_availability_id'),
    sa.UniqueConstraint('venue_id', 'venue_availability_date', name='uq_venue_date')
    )
    op.create_table('MatchResult',
    sa.Column('matchresult_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('toss_winner', sa.Integer(), nullable=False),
    sa.Column('toss_decision', sa.Enum('BATTING', 'FIELDING', name='tossdecision'), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('result_type', sa.Enum('COMPLETED', 'ABANDONED', name='resulttype'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['Match.match_id'], ),
    sa.PrimaryKeyConstraint('matchresult_id'),
    sa.UniqueConstraint('match_id')
    )
    op.alter_column('User', 'user_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'user_role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('USER', 'ADMIN', 'VENUE_MANAGER', 'SCORE_UPDATER', name='userrole'),
               postgresql_using='user_role::userrole',
               existing_nullable=True)
    op.create_index(op.f('ix_User_user_email'), 'User', ['user_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = postgresql.ENUM('USER', 'ADMIN', 'VENUE_MANAGER', 'SCORE_UPDATER', name='userrole')

    op.drop_index(op.f('ix_User_user_email'), table_name='User')
    op.alter_column('User', 'user_role',
               existing_type=sa.Enum('USER', 'ADMIN', 'VENUE_MANAGER', 'SCORE_UPDATER', name='userrole'),
               type_=sa.VARCHAR(),
               postgresql_using='user_role::text',
               existing_nullable=True)
    op.alter_column('User', 'user_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('MatchResult')
    op.drop_table('Venue_Avaialability')
    op.drop_table('PointsTable')
    op.drop_table('Match')
    op.drop_table('Venue')
    op.drop_table('Teams')
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
