"""Venue, Venueavbailabitility, Match Tables Added

Revision ID: fcf4230a80bd
Revises: c4ece44f5237
Create Date: 2026-04-17 16:20:18.243214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision: str = 'fcf4230a80bd'
down_revision: Union[str, Sequence[str], None] = 'c4ece44f5237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Venue',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('venue_name', sa.String(), nullable=False),
    sa.Column('venue_address', sa.String(), nullable=True),
    sa.Column('Venue_Capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('venue_id'),
    sa.UniqueConstraint('venue_name')
    )
    op.create_table('Match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team1_id', sa.Integer(), nullable=False),
    sa.Column('team2_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.String(), nullable=False),
    sa.Column('match_status', sa.Enum('STARTED', 'ABANDONED', 'IN_PROGESS', 'YET_TO_START', name='matchstatus'), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.venue_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('Venue_Avaialability',
    sa.Column('venue_availability_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('venue_availability_date', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.venue_id'], ),
    sa.PrimaryKeyConstraint('venue_availability_id')
    )
    user_role_enum = postgresql.ENUM('ADMIN', 'USER', 'ORGANIZER', name='user_role')
    user_role_enum.create(op.get_bind())
    op.alter_column('User', 'user_role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('USER', 'ADMIN', 'VENUE_MANAGER', 'SCORE_UPDATER', name='userrole'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'user_role',
               existing_type=sa.Enum('USER', 'ADMIN', 'VENUE_MANAGER', 'SCORE_UPDATER', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_table('Venue_Avaialability')
    op.drop_table('Match')
    op.drop_table('Venue')
    # ### end Alembic commands ###
